### PR TITLE
adding token expiration

### PR DESCRIPTION
**Pull request by Amrani-Farouk-Hossam-Eddine**
i added token expiration when createing a token and handle it in the LoginSinUp.jsx page, and updated the slices when the case is rejected isLoading should be false

### CODE REVIEW

**Comment by Saksham2k3s** [comment]
Hii @Amrani-Farouk-Hossam-Eddine , I've merged your pull request but encountering one issue now related to useHistory hook
. Could you please check it? 
usehistory_error

**Comment by Saksham2k3s** [comment]
I think you should use useNavigate instead of useHistory

**Comment by Amrani-Farouk-Hossam-Eddine** [comment]
I usully use useNavigate this time i decided to try useHistory

**Comment by Saksham2k3s** [comment]
But this is giving error, Could you please correct it

**Comment by Amrani-Farouk-Hossam-Eddine** [comment]
i correct it, you can see it on the pull requests

**Pull request merged**
